# Generated by Django 3.1.7 on 2021-05-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('numero_wspp', models.PositiveBigIntegerField()),
                ('link_facebook', models.URLField()),
            ],
            options={
                'verbose_name': 'Info Contacto',
                'ordering': ['-direccion'],
            },
        ),
        migrations.CreateModel(
            name='ListadoAccesorios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Listado Accesorio',
                'verbose_name_plural': 'Accesorios',
                'ordering': ['-descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ListadoEquipamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Listado Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['-descripcion'],
            },
        ),
    ]
