# Generated by Django 3.1.7 on 2021-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaProductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='core', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Galeria Productos',
                'verbose_name_plural': 'Galeria Productos',
            },
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-direccion'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contacto'},
        ),
        migrations.AlterModelOptions(
            name='listadoaccesorios',
            options={'verbose_name': 'Listado Accesorio', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='listadoequipamiento',
            options={'verbose_name': 'Listado Equipamiento', 'verbose_name_plural': 'Equipamientos'},
        ),
    ]
