# Generated by Django 3.1.7 on 2021-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210506_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaMotorHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='core', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Galeria MotorHome',
                'verbose_name_plural': 'Galeria MotorHome',
            },
        ),
        migrations.CreateModel(
            name='GaleriaOffRoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='core', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Galeria OffRoad',
                'verbose_name_plural': 'Galeria OffRoad',
            },
        ),
        migrations.CreateModel(
            name='GaleriaPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='core', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Galeria Popup',
                'verbose_name_plural': 'Galeria Popup',
            },
        ),
    ]
