# Generated by Django 3.1.7 on 2023-05-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230506_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriaoffroad',
            options={'ordering': ['orden'], 'verbose_name': 'Galeria Camiones', 'verbose_name_plural': 'Galeria Camiones'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='mensaje_wspp',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='direccion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='link_facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='link_instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_wspp',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
