# Generated by Django 3.1.7 on 2023-05-10 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230509_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['-localidad'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'Contacto'},
        ),
    ]
