# Generated by Django 3.1.7 on 2023-05-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230509_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriamotorhome',
            name='titulo_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='galeriaoffroad',
            name='titulo_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='galeriapopup',
            name='titulo_card',
            field=models.CharField(default='', max_length=100),
        ),
    ]
