# Generated by Django 3.1.7 on 2023-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230522_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='core', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Portada',
                'verbose_name_plural': 'Portada',
            },
        ),
    ]
