# Generated by Django 3.1.7 on 2023-05-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portada',
            options={'ordering': ['-orden'], 'verbose_name': 'Portada', 'verbose_name_plural': 'Portada'},
        ),
        migrations.AddField(
            model_name='portada',
            name='orden',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
